import { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { OBJLoader } from "three/examples/jsm/loaders/OBJLoader.js";
import { STLLoader } from "three/examples/jsm/loaders/STLLoader.js";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls.js";
import { TransformControls } from "three/examples/jsm/controls/TransformControls.js";
import { loadModelAsset, loadModelIndex } from "./modelAssetLoader";

type ManifestItem = { id:string; name:string; quantity:number; asset:string };
type SceneItem = { uid:string; asset:string; name:string; object:THREE.Object3D; locked:boolean; visible:boolean };
type Mode = "translate"|"rotate"|"scale";
const ALIASES:Record<string,string>={"Drone airframe":"drone","CUBE Orange ADS-B":"cube-orange","Here3 GPS":"here3","MK32 HM30 Air Unit":"hm30","SIYI ZR10":"zr10","Matek BEC12S PRO":"matek-bec","PM07 Power Module":"pm07","TATTU 22000 mAh battery":"tattu","4S avionics battery":"avionics-battery","SunnySky motor":"motor","AT115A ESC":"esc","Savox servo":"servo","Holybro pitot tube":"pitot","Holybro MS5525DSO module":"airspeed-module","Eagle Eye LED":"led","Emergency Stop":"estop","Two-blade 20x10 propeller":"propeller","Hobbywing UBEC":"hobbywing-ubec","Jetson carrier assembly":"jetson-orin-nx","SIYI 4-18S BEC HM30":"siyi-bec"};
const parseCsv=(text:string):ManifestItem[]=>text.trim().split(/\r?\n/).slice(1).map(row=>{const c=row.split(",");return{id:c[0],name:c[1],quantity:Number(c[2]),asset:ALIASES[c[1]]||c[1]}});

export default function App(){
 const mount=useRef<HTMLDivElement>(null),engine=useRef<any>(null);const [manifest,setManifest]=useState<ManifestItem[]>([]),[placed,setPlaced]=useState<SceneItem[]>([]),[selected,setSelected]=useState<SceneItem|null>(null),[mode,setMode]=useState<Mode>("translate"),[status,setStatus]=useState("Modellar tayyorlanmoqda…"),[opacity,setOpacity]=useState(.28),[wireframe,setWireframe]=useState(false),[search,setSearch]=useState("");const[,refresh]=useState(0);
 useEffect(()=>{fetch("/data/component_manifest.csv").then(r=>r.text()).then(t=>setManifest(parseCsv(t)))},[]);
 useEffect(()=>{if(!mount.current)return;const host=mount.current,scene=new THREE.Scene();scene.background=new THREE.Color(0x071018);const camera=new THREE.PerspectiveCamera(45,host.clientWidth/host.clientHeight,.1,100000);camera.position.set(3200,2200,3200);const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xbfe8ff,0x18232b,2.2));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(2500,4000,1800);scene.add(sun);scene.add(new THREE.GridHelper(7000,70,0x2d6c7b,0x18313a),new THREE.AxesHelper(500));const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;const transform=new TransformControls(camera,renderer.domElement);transform.setSize(.75);scene.add(transform.getHelper());transform.addEventListener("dragging-changed",(e:any)=>orbit.enabled=!e.value);transform.addEventListener("objectChange",()=>{refresh(v=>v+1);save()});const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();
  function select(item:SceneItem|null){setSelected(item);transform.detach();if(item&&!item.locked)transform.attach(item.object)}
  function save(){const data=(engine.current?.items||[]).filter((x:SceneItem)=>x.asset!=="drone").map((x:SceneItem)=>({asset:x.asset,name:x.name,position:x.object.position.toArray(),rotation:[x.object.rotation.x,x.object.rotation.y,x.object.rotation.z],scale:x.object.scale.toArray(),visible:x.visible,locked:x.locked}));localStorage.setItem("uav-layout-v2",JSON.stringify(data))}
  function click(e:PointerEvent){if(transform.dragging)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const roots:THREE.Object3D[]=engine.current?.items.map((x:SceneItem)=>x.object).filter((x:THREE.Object3D)=>x.visible)||[],hit=ray.intersectObjects(roots,true)[0];if(!hit){select(null);return}let o:THREE.Object3D=hit.object;while(o.parent&&!roots.includes(o))o=o.parent;select(engine.current.items.find((x:SceneItem)=>x.object===o)||null)}
  renderer.domElement.addEventListener("pointerdown",click);const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};window.addEventListener("resize",resize);let frame=0;const animate=()=>{frame=requestAnimationFrame(animate);orbit.update();renderer.render(scene,camera)};animate();engine.current={scene,camera,renderer,orbit,transform,items:[],select,save};setStatus("Tayyor — komponent tanlang");return()=>{cancelAnimationFrame(frame);window.removeEventListener("resize",resize);renderer.domElement.removeEventListener("pointerdown",click);renderer.dispose();host.removeChild(renderer.domElement)}},[]);
 useEffect(()=>{engine.current?.transform.setMode(mode)},[mode]);
 useEffect(()=>{const keys=(e:KeyboardEvent)=>{if((e.target as HTMLElement).tagName==="INPUT")return;const next:Record<string,Mode>={w:"translate",e:"rotate",r:"scale"};if(next[e.key.toLowerCase()])setMode(next[e.key.toLowerCase()])};window.addEventListener("keydown",keys);return()=>window.removeEventListener("keydown",keys)},[]);
 async function add(asset:string,name:string,restore?:any){const e=engine.current;if(!e)return;setStatus(`${name} yuklanmoqda…`);try{const spec=(await loadModelIndex())[asset];if(!spec)throw new Error("model indeksda yo‘q");const data=await loadModelAsset(spec);let object:THREE.Object3D;if(spec.format==="stl"){const g=new STLLoader().parse(data);g.computeVertexNormals();object=new THREE.Mesh(g,new THREE.MeshStandardMaterial({color:0x78909c,roughness:.72,transparent:true,opacity}))}else object=new OBJLoader().parse(new TextDecoder().decode(data));object.traverse((o:any)=>{if(o.isMesh)o.material=new THREE.MeshStandardMaterial({color:asset==="jetson-orin-nx"?0x2e8b57:0x7eb6c2,metalness:.12,roughness:.58})});if(asset==="drone"){const size=new THREE.Vector3();new THREE.Box3().setFromObject(object).getSize(size);object.scale.setScalar(3500/Math.max(size.x,size.z));object.traverse((o:any)=>{if(o.isMesh){o.material.transparent=true;o.material.opacity=opacity;o.material.wireframe=wireframe}})}else{const size=new THREE.Vector3();new THREE.Box3().setFromObject(object).getSize(size);if(Math.max(size.x,size.y,size.z)>500)object.scale.setScalar(100/Math.max(size.x,size.y,size.z));object.position.copy(e.orbit.target);object.position.y+=150}if(restore){object.position.fromArray(restore.position);object.rotation.set(restore.rotation[0],restore.rotation[1],restore.rotation[2]);object.scale.fromArray(restore.scale);object.visible=restore.visible!==false}const item:SceneItem={uid:crypto.randomUUID(),asset,name,object,locked:restore?.locked||asset==="drone",visible:restore?.visible!==false};e.scene.add(object);e.items.push(item);setPlaced([...e.items]);e.select(item);e.save();setStatus(`${name} sahnaga qo‘shildi`)}catch(err:any){setStatus(`Xato: ${name} — ${err.message}`)}}
 useEffect(()=>{if(manifest.length&&engine.current&&!engine.current.items.length){add("drone","Drone airframe");JSON.parse(localStorage.getItem("uav-layout-v2")||"[]").forEach((x:any)=>add(x.asset,x.name,x))}},[manifest]);
 function remove(){if(!selected||selected.asset==="drone")return;const e=engine.current;e.transform.detach();e.scene.remove(selected.object);e.items=e.items.filter((x:SceneItem)=>x!==selected);setPlaced([...e.items]);setSelected(null);e.save()}
 function duplicate(){if(!selected||selected.asset==="drone")return;const x=selected,o=x.object.clone(true);o.position.x+=100;const n={...x,uid:crypto.randomUUID(),object:o,name:x.name+" nusxa"};engine.current.scene.add(o);engine.current.items.push(n);setPlaced([...engine.current.items]);engine.current.select(n);engine.current.save()}
 function toggleLock(){if(!selected)return;selected.locked=!selected.locked;engine.current.select(selected);refresh(v=>v+1);engine.current.save()}function toggleVisible(){if(!selected)return;selected.visible=!selected.visible;selected.object.visible=selected.visible;refresh(v=>v+1);engine.current.save()}
 function view(kind:string){const e=engine.current,t=e.orbit.target,d=4500,pos:any={top:[0,d,.01],front:[0,500,d],back:[0,500,-d],left:[-d,500,0],right:[d,500,0],perspective:[3200,2200,3200]}[kind];e.camera.position.set(t.x+pos[0],t.y+pos[1],t.z+pos[2]);e.camera.lookAt(t);e.orbit.update()}
 useEffect(()=>{const d=engine.current?.items.find((x:SceneItem)=>x.asset==="drone");d?.object.traverse((o:any)=>{if(o.isMesh){o.material.opacity=opacity;o.material.wireframe=wireframe}})},[opacity,wireframe]);
 function download(name:string,data:string,type:string){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([data],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}function exportJson(){download("uav-layout.json",JSON.stringify(engine.current.items.map((x:SceneItem)=>({name:x.name,asset:x.asset,position:x.object.position.toArray(),rotation:x.object.rotation.toArray().slice(0,3),scale:x.object.scale.toArray()})),null,2),"application/json")}function exportPng(){const e=engine.current;e.renderer.render(e.scene,e.camera);const a=document.createElement("a");a.href=e.renderer.domElement.toDataURL("image/png");a.download="uav-3d-layout.png";a.click()}const count=(asset:string)=>placed.filter(x=>x.asset===asset).length;
 return <div className="app"><header><div><span className="kicker">3.5 M TWIN-MOTOR UAV</span><h1>Dron avionika 3D editor</h1></div><div className="toolbar"><button onClick={()=>setMode("translate")} className={mode==="translate"?"active":""}>W Ko‘chirish</button><button onClick={()=>setMode("rotate")} className={mode==="rotate"?"active":""}>E Aylantirish</button><button onClick={()=>setMode("scale")} className={mode==="scale"?"active":""}>R Masshtab</button><button onClick={exportJson}>JSON</button><button onClick={exportPng}>PNG</button></div></header><div className="workspace"><aside className="panel left"><h2>Komponentlar</h2><input placeholder="Qidirish…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="parts">{manifest.filter(x=>x.asset!=="drone"&&x.name.toLowerCase().includes(search.toLowerCase())).map(x=><div className="part" key={x.id}><div><b>{x.name}</b><small>{count(x.asset)} / {x.quantity} sahnada</small></div><button disabled={count(x.asset)>=x.quantity} onClick={()=>add(x.asset,x.name)}>+ Qo‘shish</button></div>)}</div></aside><main className="viewport"><div ref={mount} className="canvas"/><div className="views">{[["perspective","3D"],["top","Tepa"],["front","Old"],["back","Orqa"],["left","Chap"],["right","O‘ng"]].map(v=><button key={v[0]} onClick={()=>view(v[0])}>{v[1]}</button>)}</div><div className="status">{status}</div></main><aside className="panel right"><h2>Tanlangan obyekt</h2>{selected?<><h3>{selected.name}</h3><div className="actions"><button onClick={toggleLock}>{selected.locked?"🔒 Qulfni och":"🔓 Qulflash"}</button><button onClick={toggleVisible}>{selected.visible?"Yashirish":"Ko‘rsatish"}</button><button onClick={duplicate}>Nusxalash</button><button className="danger" onClick={remove}>O‘chirish</button></div><TransformEditor item={selected} onChange={()=>{refresh(v=>v+1);engine.current.save()}}/></>:<p>Sahnadagi obyektni bosing.</p>}<hr/><h2>Dron korpusi</h2><label>Shaffoflik <b>{Math.round(opacity*100)}%</b><input type="range" min="0" max="1" step=".01" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label><label className="check"><input type="checkbox" checked={wireframe} onChange={e=>setWireframe(e.target.checked)}/> Wireframe</label><p className="hint">Sichqoncha bilan kamera boshqariladi. Obyektni tanlab W, E yoki R rejimidan foydalaning.</p></aside></div></div>}
function TransformEditor({item,onChange}:{item:SceneItem,onChange:()=>void}){const groups:[string,THREE.Vector3,string][]=[["Joylashuv (mm)",item.object.position,"position"],["Aylanish (°)",new THREE.Vector3(THREE.MathUtils.radToDeg(item.object.rotation.x),THREE.MathUtils.radToDeg(item.object.rotation.y),THREE.MathUtils.radToDeg(item.object.rotation.z)),"rotation"],["Masshtab",item.object.scale,"scale"]];function edit(kind:string,axis:"x"|"y"|"z",value:number){if(kind==="rotation")(item.object.rotation as any)[axis]=THREE.MathUtils.degToRad(value);else(item.object as any)[kind][axis]=value;onChange()}return <>{groups.map(([title,v,kind])=><fieldset key={kind}><legend>{title}</legend>{(["x","y","z"] as const).map(a=><label key={a}>{a.toUpperCase()}<input type="number" step={kind==="scale"?.05:1} value={Number(v[a].toFixed(2))} onChange={e=>edit(kind,a,Number(e.target.value))}/></label>)}</fieldset>)}</>}
